
[en]
  title = "IRA - Information Retrieval and Analytics"
  LanguageName = "English"
  weight = 1

[pt]
  title = "Claridade" # just for the sake of showing this is possible
  LanguageName = "Português"
  weight = 2
  
